---
title: "Estadísticas policiales"
output:
  flexdashboard::flex_dashboard:
    theme:
      version: 5
      bg: "#E8E8E8"
      fg: "#000000" 
      primary: "#000000"
      navbar-bg: "#000000"
      base_font: 
        google: Prompt
      heading_font:
        google: Sen
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: JetBrains Mono
          local: false
    orientation: columns
    vertical_layout: fill
    logo: "descarga.png" 
runtime: shiny
resource_files:
- "placa-lg-removebg-preview (2).png"
- distritos_simplificados.geojson
    

---

```{r setup, include=FALSE}
library(flexdashboard)
library(flexdashboard)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(plotly)
library(DT)
library(readr)
library(readxl)
library(lubridate)
library(tidyverse)
library(sf)
library(leaflet)
library(flexdashboard)
library(stringi)
library(shiny)
```

Mapa
===============================================================

```{r carga de datos}
estadisticas <- read_xls(path="estadisticaspoliciales2021.xls")
estadisticas=subset(estadisticas, select=c("Delito", "Fecha", "Victima", "Edad", "Genero", "Provincia", "Canton", "Distrito"))
estadisticas$Fecha <- as.Date(estadisticas$Fecha, format = "%d/%m/%Y")

distritos <-
  st_read(dsn = "distritos_simplificados.geojson", quiet = TRUE) %>%
  st_transform(4326)
```


```{r lista-delito}
lista_delito <- unique(estadisticas$Delito)
lista_delito <- sort(lista_delito)
lista_delito <- c("Todos", lista_delito)
```

```{r lista-victima}
lista_victima <- unique(estadisticas$Victima)
lista_victima <- sort(lista_victima)
lista_victima <- c("Todos", lista_victima)
```

```{r lista-genero}
lista_genero <- unique(estadisticas$Genero)
lista_genero <- sort(lista_genero)
lista_genero <- c("Todos", lista_genero)
```

```{r lista-edad}
lista_edad <- unique(estadisticas$Edad)
lista_edad <- sort(lista_edad)
lista_edad <- c("Todos", lista_edad)
```

Column {data-width=100}
-----------------------------------------------------------------------

### Filtro

```{r filtro-delito}
selectInput(
  inputId = "Delito",
  label = "Tipo de delito",
  choices = lista_delito,
  selected = "Todos"
)
```

``` {r filtro-victima}
selectInput(
  inputId = "Victima",
  label = "Víctima",
  choices = lista_victima,
  selected = "Todos"
)
```

``` {r filtro-genero}
selectInput(
  inputId = "Genero",
  label = "Género",
  choices = lista_genero,
  selected = "Todos"
)
```

```{r filtro-edad}
selectInput(
  inputId = "Edad",
  label = "Edad",
  choices = lista_edad,
  selected = "Todos"
)
```

```{r filtros}
filtrarEstadisticas <- reactive ({
  Estadisticas_filtradas <- estadisticas
  if (input$Delito != "Todos") {
    Estadisticas_filtradas <-
      Estadisticas_filtradas %>%
      filter(Delito == input$Delito)
    
  if (input$Delito == "Todos") {
    Estadisticas_filtradas <-
      Estadisticas_filtradas %>%
      lista_delito <- unique(estadisticas$Delito)
      lista_delito <- sort(lista_delito)
      lista_delito <- c("Todos", lista_delito)
      
    updateSelectInput(
        session,
        "Delito",
        label = "Delito",
        choices = lista_delito,
        selected = "Todos"
    )
  }}
  
  if (input$Victima != "Todos") {
    Estadisticas_filtradas <-
      Estadisticas_filtradas %>%
      filter(Victima == input$Victima)
    
  if (input$Victima == "Todos") {
    Estadisticas_filtradas <-
      Estadisticas_filtradas %>%
      lista_victima <- unique(estadisticas$Victima)
      lista_victima <- sort(lista_victima)
      lista_victima <- c("Todos", lista_victima)
      
    updateSelectInput(
        session,
        "Victima",
        label = "Víctima",
        choices = lista_victima,
        selected = "Todos"
    )
  }}
  
  if (input$Genero != "Todos") {
    Estadisticas_filtradas <-
      Estadisticas_filtradas %>%
      filter(Genero == input$Genero)
    
  if (input$Genero == "Todos") {
    Estadisticas_filtradas <-
      Estadisticas_filtradas %>%
      lista_genero <- unique(estadisticas$Genero)
      lista_genero <- sort(lista_genero)
      lista_genero <- c("Todos", lista_genero)
      
    updateSelectInput(
        session,
        "Genero",
        label = "Género",
        choices = lista_genero,
        selected = "Todos"
    )
  }}
  
  if (input$Edad != "Todos") {
    Estadisticas_filtradas <-
      Estadisticas_filtradas %>%
      filter(Edad == input$Edad)
    
  if (input$Edad == "Todos") {
    Estadisticas_filtradas <-
      Estadisticas_filtradas %>%
      lista_edad <- unique(estadisticas$Edad)
      lista_edad <- sort(lista_edad)
      lista_edad <- c("Todos", lista_edad)
      
    updateSelectInput(
        session,
        "Edad",
        label = "Edad",
        choices = lista_edad,
        selected = "Todos"
    )
  }}
  return(Estadisticas_filtradas)
})
```
Universidad de Costa Rica

Escuela de Geografía

Proyecto Final

Procesamiento de datos geográficos

I-ciclo 2022

Elaborado por: 

Joselin Guido, Natalia Martinez.

Column {data-width=550}
-----------------------------------------------------------------------

### **Mapa por cantidad de delitos en los distritos de Costa Rica**

```{r}
distritos <-
  distritos%>%
  mutate(distrito_normalizado = tolower(stri_trans_general(distrito, id = "Latin-ASCII")))
```

```{r, correccion_datos, message=FALSE, warning=FALSE}
estadisticas <-
 estadisticas %>%
  mutate(Distrito = if_else(Distrito == "CAIRO", "EL CAIRO", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "FORTUNA", "LA FORTUNA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "HORQUETAS", "LAS HORQUETAS", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "GENERAL", "EL GENERAL", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "SAN JOSE DE LA MONTA?A", "SAN JOSE DE LA MONTANA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "MACACOMA", "MACACONA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "CEIBA", "LA CEIBA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "CORTES", "PUERTO CORTES", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "LA AMISTAD", "LA  AMISTAD", Distrito)) %>% 
  mutate(Distrito = if_else(Distrito == "SAN JOSE (PIZOTE)", "SAN JOSE O PIZOTE", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "LOS ANGELES", "ANGELES", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "ASUNCION", "LA ASUNCION", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "MASTATE", "EL MASTATE", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "UNION", "LA UNION", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "MATA PLATANO", "MATA DE PLATANO", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "AGUA BUENA", "AGUABUENA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "PALMERA", "LA PALMERA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "TIGRA", "LA TIGRA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "MERECEDES", "MERCEDES", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "DRAKE", "BAHIA DRAKE", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "GRANJA", "LA GRANJA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "CURE?A", "CURENA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "EL CHIRRIPO", "CHIRRIPO", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "LA LEGUA", "LEGUA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "TAPEZCO", "TAPESCO", Distrito))
```

```{r}
estadisticas <-
  estadisticas%>%
  mutate(distrito_normalizado = tolower(stri_trans_general(Distrito, id = "Latin-ASCII")))
```

```{r}
estadisticas <-
  estadisticas %>%
  left_join(
    dplyr::select(
      st_drop_geometry(distritos),
      cod_canton,
      distrito_normalizado
    ),
    by = "distrito_normalizado",
    copy = FALSE,
    keep = FALSE
  )
```

```{r}
delitos_x_distrito <-
  estadisticas %>%
  count(distrito_normalizado, name = "delitos")
```

```{r}
distritos_delitos <-
  distritos %>%
  left_join(
    delitos_x_distrito,
    by = "distrito_normalizado",
    copy = FALSE,
    keep = FALSE
  )
```

```{r Union de los distritos y las estadisticas}

estadisticas <-
  estadisticas %>%
  left_join(
    dplyr::select(
      st_drop_geometry(distritos),
      codigo_dta,
      cod_canton,
      distrito_normalizado
    ),
    by = c("cod_canton" = "cod_canton", "distrito_normalizado" = "distrito_normalizado"),
    copy = FALSE,
    keep = FALSE
  )

delitos_x_distrito <-
  estadisticas %>%
  count(codigo_dta, name = "delitos")

distritos_delitos <-
  distritos %>%
  left_join(delitos_x_distrito,
            by = "codigo_dta",
            copy = FALSE,
            keep = FALSE) %>%
  mutate(delitos = ifelse(is.na(delitos), 0, delitos))
```


```{r para los colores}
colores_distritos_delitos <-
  colorNumeric(palette = "Purples",
               domain = distritos_delitos$delitos,
              )
```

```{r}
renderLeaflet({
  estadisticas <- filtrarEstadisticas()
  
  delitos_x_distrito <-
  estadisticas %>%
  count(codigo_dta, name = "delitos")
distritos_delitos <-
  distritos %>%
  left_join(
    delitos_x_distrito,
    by = "codigo_dta",
    copy = FALSE,
    keep = FALSE
  ) %>%
  mutate(delitos = ifelse(is.na(delitos), 0, delitos))
  
leaflet() %>%
  setView(
    lng = -84.19452,
    lat = 9.572735,
    zoom = 7) %>%
  addTiles(group = "OpenStreetMap") %>%
  addPolygons(
    data = distritos_delitos,
    fillColor = ~ colores_distritos_delitos(distritos_delitos$delitos),
    fillOpacity = 0.8,
    color = "black",
    stroke = TRUE,
    weight = 1.0,
    popup = paste(
      paste(
        "<strong>Distrito:</strong>",
        distritos_delitos$distrito
      ),
      paste(
        "<strong>Delitos:</strong>",
        distritos_delitos$delitos
      ),
      paste(
        "<strong>Cantón:</strong>",
        distritos_delitos$canton
      ),
      paste(
        "<strong>Provincia:</strong>",
        distritos_delitos$provincia
      ),
      sep = '<br/>'
    ),
    group = "Distritos"
  ) %>%
  addLayersControl(
    baseGroups = c("OpenStreetMap"),
    overlayGroups = c("Distritos")
  ) %>%
  addLegend(
    position = "bottomleft",
    pal = colores_distritos_delitos,
    values = distritos_delitos$delitos,
    group = "Delitos",
    title = "Cantidad de delitos"
  )
})
```

Tabla de datos OIJ
===============================================================
Row {.tabset} 
----------------------------------------------------------------------------
### **Tabla interactiva de las estadísticas policiales registradas por el (OIJ) en el 2021**

```{r tabla, message=FALSE, echo=FALSE, warning=FALSE}
renderDT({
  estadisticas <- filtrarEstadisticas()
estadisticas %>%
  dplyr::select(Delito, Fecha, Victima, Edad, Genero, Provincia, Canton, Distrito) %>%
  datatable(colnames = c(
    "Delito",
    "Fecha",
    "Víctima",
    "Edad",
    "Género",
    "Provincia",
    "Cantón",
    "Distrito"
  ),
options = list(
  language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
))})
```

### Fuente de datos

**Fuente:[Datos abiertos Organismo de Investigación Judicial(OIJ)] (https://sitiooij.poder-judicial.go.cr/index.php/ayuda/servicios-policiales/servicios-a-organizaciones/indice-de-transparencia-del-sector-publico-costarricense/datos-abiertos)**

Delitos
===============================================================
Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### **Cantidad de delitos por tipo de delito**

```{r grafico-cantidad-delitos}
renderPlotly({
  estadisticas <- filtrarEstadisticas()
  
grafico_delitos <-
  estadisticas %>%
  count(Delito) %>%
  ggplot(aes(x = reorder(Delito, n), y = n)) +
  geom_bar(stat = "identity",fill= "cadetblue4") +
  ggtitle("Cantidad de delitos por tipo de delito") + 
  xlab("Tipo de delito") +
  ylab("Cantidad") +
  coord_flip() +
  theme_minimal()
ggplotly(grafico_delitos)%>% 
  config(locale = 'es')
}) 
```


### **Cantidad de delitos por tipo de víctima**

```{r message=FALSE, warning=FALSE, echo=FALSE}
renderPlotly({
  estadisticas <- filtrarEstadisticas()
  
grafico_delitos <-
  estadisticas %>%
  count(Victima) %>%
  ggplot(aes(x = reorder(Victima, n), y = n)) +
  geom_bar(stat = "identity", fill=c(1:5)) +
  xlab("Tipo de delito") +
  ylab("Cantidad") +
   ggtitle("Cantidad de delitos por tipo de víctima") +
  coord_flip()
  theme_minimal()
ggplotly(grafico_delitos)%>%
  config(locale = 'es')
})
```


### **Cantidad de delitos por mes**
```{r}
Del_mes <- estadisticas %>%
  dplyr::select(Fecha, Delito)
```


```{r grafico-delitos-mes, message=FALSE}
renderPlotly({
  estadisticas <- filtrarEstadisticas()

graph2 <- 
Del_mes %>% mutate(mes = month(Fecha, label = FALSE)) %>%
  ggplot() +
  geom_bar(aes(x = mes), fill = "coral2", color = "coral2") + 
  ggtitle("Cantidad de delitos por mes") + 
  xlab("Mes (1-11)") + 
  ylab("Cantidad") + 
  theme_minimal() 
ggplotly(graph2) %>%
  config(locale = 'es')
})
```


### **Cantidad de delitos por género**

```{r delitos-genero}
renderPlotly({
  estadisticas <- filtrarEstadisticas()
  
ggplot2_barras_apiladas_cantidad <-
  estadisticas %>%
  ggplot(aes(x = estadisticas$Delito, fill = estadisticas$Genero)) +
  geom_bar(position = "fill") +
  coord_flip()+
  xlab("Delito") +
  ylab("Proporcion") +
  ggtitle("Proporción de delitos por género") +
  labs(fill = "Género") +
  theme_minimal()
ggplotly(ggplot2_barras_apiladas_cantidad) %>% 
  config(locale = 'es')
})
```


### **Cantidad de delitos por edad**

```{r delitos-edad}
renderPlotly({
  estadisticas <- filtrarEstadisticas()
  
ggplot2_barras_apiladas_cantidad <-
  estadisticas %>%
  ggplot(aes(x = estadisticas$Delito, fill = estadisticas$Edad)) +
  geom_bar(position = "fill") +
  ggtitle("Proporcion de delitos por edad")+
  xlab("Tipo de Delito") +
  ylab("Proporcion") +
  labs(fill = "Edad") +
  theme_minimal()+
  coord_flip()
ggplotly(ggplot2_barras_apiladas_cantidad) %>% 
  config(locale = 'es')
})
```

